{{ config(materialized="table") }}

select
    COALESCE("company_account", '')                     as company_account,
    COALESCE("merchant_account", '')                    as merchant_account,
    COALESCE("psp_reference", '')                       as psp_reference,
    COALESCE("merchant_reference", 0)                   as merchant_reference,
    COALESCE("payment_method", '')                      as payment_method,
    CAST(creation_date as DATE)                         as creation_date,
    COALESCE("time_zone", '')                           as timezone,
    COALESCE("currency", '')                            as currency ,
    COALESCE("amount", 0)                               as main_amount,
    COALESCE("type", '')                                as type,
    COALESCE("risk_scoring", 0)                         as risk_scoring,
    COALESCE("shopper_interaction", '')                 as shopper_interaction,
    COALESCE("shopper_name", '')                        as shopper_name,
    COALESCE("shopper_pan", 0)                          as shopper_pan,
    COALESCE("shopper_ip", '')                          as shopper_ip,
    COALESCE("shopper_country", '')                     as shopper_country,
    COALESCE("issuer_name", '')                         as issuer_name,
    COALESCE("issuer_id", 0)                            as issuer_id,
    COALESCE("issuer_city", '')                         as issuer_city,
    COALESCE("issuer_country", '')                      as issuer_country,
    COALESCE("acquirer_response", '')                   as acquirer_response,
    COALESCE("authorisation_code", '')                  as authorisation_code,
    COALESCE("shopper_email", '')                       as shopper_email,
    COALESCE("shopper_reference", '')                   as shopper_reference,
    COALESCE("3d_directory_response", '')               as "3d_directory_response",
    COALESCE("3d_authentication_response", '')          as "3d_authentication_response",
    COALESCE("cvc2_response", 0)                        as cvc2_response,
    COALESCE("avs_response", 0)                         as avs_response,
    COALESCE("billing_street", '')                      as billing_street,
    COALESCE("billing_house_number___name", '')         as billing_house_number___name,
    COALESCE("billing_city", '')                        as billing_city,
    COALESCE("billing_postal_code___zip", '')           as billing_postal_code___zip,
    COALESCE("billing_state___province", '')            as billing_state___province,
    COALESCE("billing_country", '')                     as billing_country,
    COALESCE("delivery_street", '')                     as delivery_street,
    COALESCE("delivery_house_number___name", '')        as delivery_house_number___name,
    COALESCE("delivery_city", '')                       as delivery_city,
    COALESCE("delivery_postal_code___zip", 0)           as delivery_postal_code___zip,
    COALESCE("delivery_state___province", '')           as delivery_state___province,
    COALESCE("delivery_country", '')                    as delivery_country,
    COALESCE("acquirer_reference", '')                  as acquirer_reference,
    COALESCE("payment_method_variant", '')              as payment_method_variant ,
    COALESCE("raw_acquirer_response", '')               as raw_acquirer_response,
    COALESCE("reserved4", '')                           as reserved4,
    COALESCE("reserved5", '')                           as reserved5,
    COALESCE("reserved6", '')                           as reserved6,
    COALESCE("reserved7", '')                           as reserved7,
    COALESCE("reserved8", '')                           as reserved8,
    COALESCE("reserved9", '')                           as reserved9,
    COALESCE("reserved10" '')                           as reserved10


from adyen_received_payments_report