
version: 2

models:
  - name: adyen_settlement_report_aggregate
    descipcion: "Transformacion de adyen settlement report"
    columns:
      - name: company_account
      - name: merchant_account
      - name: country_code
      - name: store
      - name: terminal_id
      - name: batch_number
      - name: batch_closed_date
      - name: batch_closed_date_trunc
      - name: payment_method
      - name: creation_date
      - name: timezone
      - name: journal_type
      - name: gross_currency
      - name: gross_debit_gc
      - name: gross_credit_gc
      - name: exchange_rate
      - name: net_currency
      - name: net_debit_nc
      - name: net_credit_nc
      - name: bank_card_commission_nc
      - name: dcc_markup_nc
      - name: num_txs
  - name: adyen_payments_accounting_report
    columns:
      - name: company_account
      - name: merchant_account
      - name: psp_reference
      - name: merchant_reference
      - name: payment_method
      - name: booking_date
      - name: booking_date
      - name: timezone
      - name: main_currency
      - name: main_amount
      - name: payment_currency
      - name: received_pc
      - name: authorised_pc
      - name: captured_pc
      - name: payable_sc
      - name: commission_sc
      - name: markup_sc
      - name: scheme_fees_sc
      - name: interchange_sc
      - name: processing_fee_currency
      - name: processing_fee_fc
      - name: user_name
      - name: payment_method_variant
      - name: modification_merchant_reference
      - name: reserved3
      - name: reserved4
      - name: reserved5
      - name: reserved6
      - name: reserved7
      - name: reserved8
      - name: reserved9
      - name: reserved10